import test from 'node:test'; import assert from 'node:assert/strict';
const empty={budgets:[],units:[],scheduleTypes:[],hourSettings:[],calendarPeriods:[],calendarRows:[],calendarHolidays:[],salaryEntries:[],forecastEvaluations:[],holidayNames:[]};
function storage(){const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k),clear:()=>m.clear(),get writes(){return m.size;}};}
function mockRun(){let success,failure;const calls=[],pending=[];const runner={withSuccessHandler(fn){success=fn;return runner;},withFailureHandler(fn){failure=fn;return runner;},runServerFunction(action,payload){calls.push({action,payload});if(action==='getWorkStudyBootstrapData')success({ok:true,data:structuredClone(empty)});else pending.push({success,failure,action,payload});}};return {runner,calls,pending};}
async function setup(){const mock=mockRun(),ls=storage();globalThis.window={WORK_STUDY_CONFIG:{DATA_MODE:'gasSheet'},WORK_STUDY_RUNTIME_CONFIG:{writeMode:'enabled',allowLocalFallback:false},google:{script:{run:mock.runner}}};globalThis.localStorage=ls;globalThis.document={};const ds=await import(`../js/dataStore.js?gas=${Date.now()}${Math.random()}`);await ds.initDataStore();return {ds,mock,ls};}
test('gas save pending does not update cache',async()=>{const {ds,mock}=await setup();const p=ds.saveBudget({academicYear:'114',budgetName:'A',unitCodes:['U'],budgetAmount:1});assert.equal(ds.getBudgets().length,0);assert.equal(mock.pending.length,1);mock.pending[0].success({ok:true,result:{id:'B1',academicYear:'114',budgetName:'A',unitCodes:['U'],budgetAmount:1}});await p;assert.equal(ds.getBudgets()[0].id,'B1');});
test('gas save failure preserves cache',async()=>{const {ds,mock}=await setup();const p=ds.saveBudget({academicYear:'114',budgetName:'A',unitCodes:['U'],budgetAmount:1});mock.pending[0].success({ok:false,code:'DUPLICATE',message:'資料重複'});await assert.rejects(p,/資料重複/);assert.deepEqual(ds.getBudgets(),[]);});
test('gas error preserves safe code',async()=>{const {ds,mock}=await setup();const p=ds.saveBudget({});mock.pending[0].success({ok:false,code:'VALIDATION_ERROR',message:'缺少必要欄位'});await assert.rejects(p,e=>e.code==='VALIDATION_ERROR'&&e.message==='缺少必要欄位');});
test('gas mode does not mirror business data',async()=>{const {ds,mock,ls}=await setup();const p=ds.saveBudget({});mock.pending[0].success({ok:true,result:{id:'B1'}});await p;assert.equal(ls.writes,0);});
test('arbitrary GAS action is rejected before invocation',async()=>{const {ds,mock}=await setup();await assert.rejects(ds.callGasMutation('replaceCollection',{}),/不允許/);assert.equal(mock.calls.length,1);});
test('batch caches addedRecords only',async()=>{const {ds,mock}=await setup();const p=ds.saveHourSettingsBatch([{sourceId:'x'}]);mock.pending[0].success({ok:true,result:{selected:1,added:1,addedRecords:[{id:'H1'}],skipped:[{id:'H2'}]}});await p;assert.deepEqual(ds.getHourSettings().map(x=>x.id),['H1']);});
test('delete removes confirmed ids only',async()=>{const {ds,mock}=await setup();let p=ds.saveBudget({});mock.pending[0].success({ok:true,result:{id:'B1'}});await p;p=ds.saveBudget({});mock.pending[1].success({ok:true,result:{id:'B2'}});await p;const d=ds.deleteBudgets(['B1','B2']);mock.pending[2].success({ok:true,result:{deletedIds:['B1'],deletedCount:1}});await d;assert.deepEqual(ds.getBudgets().map(x=>x.id),['B2']);});
test('delete failure preserves cache',async()=>{const {ds,mock}=await setup();let p=ds.saveBudget({});mock.pending[0].success({ok:true,result:{id:'B1'}});await p;const before=JSON.stringify(ds.getBudgets()),d=ds.deleteBudgets(['B1']);mock.pending[1].failure(new Error('network'));await assert.rejects(d,/network/);assert.equal(JSON.stringify(ds.getBudgets()),before);});
test('missing google.script.run rejects explicitly',async()=>{globalThis.window={WORK_STUDY_CONFIG:{DATA_MODE:'gasSheet'},WORK_STUDY_RUNTIME_CONFIG:{allowLocalFallback:false}};globalThis.localStorage=storage();const ds=await import(`../js/dataStore.js?missing=${Date.now()}`);await assert.rejects(ds.initDataStore(),/google\.script\.run 不存在/);});
