import test from 'node:test';
import assert from 'node:assert/strict';

const empty={budgets:[],units:[],scheduleTypes:[],hourSettings:[],calendarPeriods:[],calendarRows:[],calendarHolidays:[],salaryEntries:[],forecastEvaluations:[],holidayNames:[]};
function storage(){const m=new Map();let writes=0;return {getItem:k=>m.get(k)||null,setItem:(k,v)=>{writes++;m.set(k,v);},removeItem:k=>m.delete(k),clear:()=>m.clear(),get writes(){return writes;}};}
function mockRun(data=empty){let success,failure;const calls=[],pending=[];const runner={withSuccessHandler(fn){success=fn;return runner;},withFailureHandler(fn){failure=fn;return runner;},runServerFunction(action,payload){calls.push({action,payload});if(action==='getWorkStudyBootstrapData')success({ok:true,data:structuredClone(data)});else pending.push({success,failure,action,payload});}};return {runner,calls,pending};}
async function setup(data=empty){const mock=mockRun(data),ls=storage();globalThis.window={WORK_STUDY_CONFIG:{DATA_MODE:'gasSheet'},WORK_STUDY_RUNTIME_CONFIG:{writeMode:'enabled',allowLocalFallback:false},google:{script:{run:mock.runner}},dispatchEvent(){}};globalThis.localStorage=ls;globalThis.document={body:null};globalThis.CustomEvent=class{constructor(type,init){this.type=type;this.detail=init.detail;}};const ds=await import(`../js/dataStore.js?gas=${Date.now()}${Math.random()}`);await ds.initDataStore();return {ds,mock,ls};}
function succeed(call,rows){call.success({ok:true,result:{collection:call.payload.collection,rows:structuredClone(rows),clientGeneration:call.payload.clientGeneration}});}

test('same collection debounce merges three promises into one authoritative replace',async()=>{const {ds,mock}=await setup();const p1=ds.saveBudget({academicYear:'114',budgetName:'A',unitCodes:['U'],budgetAmount:1});const id=ds.getBudgets()[0].id;const p2=ds.saveBudget({id,academicYear:'114',budgetName:'A',unitCodes:['U'],budgetAmount:2});const p3=ds.saveBudget({id,academicYear:'114',budgetName:'A',unitCodes:['U'],budgetAmount:3});assert.equal(ds.getBudgets()[0].budgetAmount,3);const flush=ds.flushCollectionSync('budgets');assert.equal(mock.pending.length,1);assert.equal(mock.pending[0].payload.rows[0].budgetAmount,3);const authoritative=[{...mock.pending[0].payload.rows[0],budgetAmount:30}];succeed(mock.pending[0],authoritative);await Promise.all([p1,p2,p3,flush]);assert.equal(ds.getBudgets()[0].budgetAmount,30);});
test('different collections keep independent request state',async()=>{const {ds,mock}=await setup();const a=ds.saveBudget({academicYear:'114',budgetName:'A',unitCodes:['U'],budgetAmount:1}),b=ds.saveUnit({unitCode:'U',unitName:'Unit'});const fa=ds.flushCollectionSync('budgets'),fb=ds.flushCollectionSync('units');assert.deepEqual(mock.pending.map(x=>x.payload.collection).sort(),['budgets','units']);mock.pending.forEach(call=>succeed(call,call.payload.rows));await Promise.all([a,b,fa,fb]);});
test('failure rolls optimistic cache back and rejects all covered mutations',async()=>{const {ds,mock}=await setup();const phases=[];ds.subscribeCollection(event=>phases.push(event.phase));const p1=ds.saveUnit({unitCode:'U',unitName:'A'}),id=ds.getUnits()[0].id,p2=ds.saveUnit({id,unitCode:'U',unitName:'B'});const flush=ds.flushCollectionSync('units');mock.pending[0].failure(new Error('network'));await assert.rejects(Promise.all([p1,p2,flush]),/network/);assert.deepEqual(ds.getUnits(),[]);assert.ok(phases.includes('rollback'));});
test('in-flight response cannot overwrite a newer optimistic generation',async()=>{const {ds,mock}=await setup();const p1=ds.saveUnit({unitCode:'U',unitName:'A'}),id=ds.getUnits()[0].id,f1=ds.flushCollectionSync('units');const p2=ds.saveUnit({id,unitCode:'U',unitName:'B'});succeed(mock.pending[0],[{...mock.pending[0].payload.rows[0],unitName:'A normalized'}]);await Promise.all([p1,f1]);assert.equal(ds.getUnits()[0].unitName,'B');await new Promise(resolve=>setTimeout(resolve,5));assert.equal(mock.pending.length,2);succeed(mock.pending[1],mock.pending[1].payload.rows);await p2;assert.equal(ds.getUnits()[0].unitName,'B');});
test('GAS bootstrap/save/success/failure never writes business localStorage',async()=>{const {ds,mock,ls}=await setup();const ok=ds.saveUnit({unitCode:'U',unitName:'A'}),f1=ds.flushCollectionSync('units');succeed(mock.pending[0],mock.pending[0].payload.rows);await Promise.all([ok,f1]);const id=ds.getUnits()[0].id,bad=ds.saveUnit({id,unitCode:'U',unitName:'B'}),f2=ds.flushCollectionSync('units');mock.pending[1].failure(new Error('no'));await assert.rejects(Promise.all([bad,f2]));assert.equal(ls.writes,0);});
test('salary batch preserves existing id, row count, composite key and direct actualAmount',async()=>{const seed=structuredClone(empty);seed.units=[{id:'UNIT_existing01',unitCode:'U',unitName:'Unit'}];seed.budgets=[{id:'BUD_existing01',academicYear:'114',budgetName:'A',unitCodes:['U'],budgetAmount:1}];seed.salaryEntries=[{id:'SALARY_existing01',academicYear:'114',year:2025,month:7,unitCode:'U',unitName:'Unit',actualHours:0,hourlyWage:200,actualAmount:1000}];const {ds,mock}=await setup(seed);const p=ds.saveSalaryEntriesBatch([{id:'SALARY_existing01',academicYear:'114',year:2025,month:7,unitCode:'U',unitName:'Unit',hourlyWage:200,actualAmount:1234}]);assert.equal(ds.getSalaryEntries().length,1);assert.equal(ds.getSalaryEntries()[0].id,'SALARY_existing01');const flush=ds.flushCollectionSync('salaryEntries');assert.equal(mock.pending[0].payload.rows[0].actualAmount,1234);succeed(mock.pending[0],mock.pending[0].payload.rows);await Promise.all([p,flush]);assert.equal(ds.getSalaryEntries()[0].actualAmount,1234);assert.deepEqual(ds.inspectSalaryEntryDuplicates(),[]);});
test('salary duplicate diagnostic reports key, ids and rowCount without mutation',async()=>{const seed=structuredClone(empty);seed.salaryEntries=[{id:'S1',academicYear:'114',year:2025,month:7,unitCode:'U'},{id:'S2',academicYear:'114',year:2025,month:7,unitCode:'U'}];const {ds}=await setup(seed);const before=structuredClone(ds.getSalaryEntries()),out=ds.inspectSalaryEntryDuplicates();assert.deepEqual(out,[{key:'114|2025|7|U',ids:['S1','S2'],rowCount:2}]);assert.deepEqual(ds.getSalaryEntries(),before);});
test('forecast GAS read and authoritative save responses normalize JSON interval strings',async()=>{const seed=structuredClone(empty);seed.forecastEvaluations=[{id:'FE_OLD',name:'Old',budget:'100',intervals:'[{"startYm":"2026-01","endYm":"2026-12","hourlyWage":"205"}]'}];const {ds,mock}=await setup(seed);assert.equal(ds.getForecastEvaluations()[0].intervals[0].hourlyWage,205);const save=ds.saveForecastEvaluation({name:'New',budget:200,intervals:[{startYm:'2027-01',endYm:'2027-12',hourlyWage:'210'}]});assert.equal(ds.getForecastEvaluations().find(row=>row.name==='New').intervals[0].hourlyWage,210);const flush=ds.flushCollectionSync('forecastEvaluations');assert.ok(Array.isArray(mock.pending[0].payload.rows.find(row=>row.name==='New').intervals));const authoritative=mock.pending[0].payload.rows.map(row=>({...row,intervals:JSON.stringify(row.intervals)}));succeed(mock.pending[0],authoritative);const [saved]=await Promise.all([save,flush]);assert.equal(saved.intervals[0].hourlyWage,210);assert.ok(Array.isArray(ds.getForecastEvaluations().find(row=>row.name==='New').intervals));});
test('arbitrary GAS action is rejected before invocation',async()=>{const {ds,mock}=await setup();await assert.rejects(ds.callGasMutation('dropEverything',{}),/不允許/);assert.equal(mock.calls.length,1);});
test('missing google.script.run rejects explicitly',async()=>{globalThis.window={WORK_STUDY_CONFIG:{DATA_MODE:'gasSheet'},WORK_STUDY_RUNTIME_CONFIG:{allowLocalFallback:false}};globalThis.localStorage=storage();globalThis.document={body:null};const ds=await import(`../js/dataStore.js?missing=${Date.now()}`);await assert.rejects(ds.initDataStore(),/google\.script\.run 不存在/);});
