import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'); const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const config=read('gas/00_Config.gs'), web=read('gas/01_WebApp.gs'), repo=read('gas/02_SheetRepository.gs'), api=read('gas/04_Api.gs'), migration=read('gas/06_Migration160.gs'), html=read('gas/Index.html'), store=read('js/dataStore.js');
test('ten table schema and intentional exclusions',()=>{assert.equal((config.match(/sheet:'\d\d_/g)||[]).length,10);assert.match(config,/budgetName','unitCodes/);const hour=config.match(/hourSettings:\{[^\n]+/)[0],cal=config.match(/calendarRows:\{[^\n]+/)[0],forecast=config.match(/forecastEvaluations:\{[^\n]+/)[0];assert.doesNotMatch(hour,/budgetId|budgetName/);assert.doesNotMatch(cal,/'note'/);assert.doesNotMatch(forecast,/budgetName/);assert.match(config,/unitCodes:true,intervals:true/);});
test('GAS shell is strict and secret-free',()=>{assert.match(html,/DATA_MODE:'gasSheet'/);assert.match(web,/allowLocalFallback:false/);assert.match(html,/\?v=<\?= assetVersion \?>/);assert.doesNotMatch(html,/PTB_SPREADSHEET_ID|Spreadsheet ID/);assert.match(html,/系統設定錯誤/);});
test('repository uses header mapping whitelist and locks',()=>{assert.match(repo,/getHeaderMap_/);assert.match(repo,/PTB_TABLES\[key\]/);assert.match(repo,/LockService\.getScriptLock/);assert.match(repo,/finally\{lock\.releaseLock/);assert.doesNotMatch(api,/payload\.sheet|payload\.sheetName/);});
test('API whitelist and collection replace actions exist',()=>{assert.match(api,/var PTB_ACTIONS=Object\.freeze/);assert.match(api,/function replaceCollection\(/);assert.match(api,/function replaceCollectionsBatch\(/);assert.match(api,/replaceCollection:replaceCollection/);assert.match(api,/replaceCollectionsBatch:replaceCollectionsBatch/);assert.match(api,/sourceHourSettingId/);});
test('calendar wage migration backs up sheets, fills rows, then removes deprecated schema',()=>{assert.match(migration,/backupMigrationSheet_/);assert.match(migration,/legacyWages/);assert.match(migration,/MIGRATION_BLOCKED/);assert.match(migration,/rewriteSheetSchema_\(calendarSheet/);assert.match(migration,/rewriteSheetSchema_\(hourSheet/);assert.match(migration,/removedDeprecatedColumn:'hourlyWage'/);assert.match(migration,/不自動虛構 mapping/);});
test('data store GAS mode has no CSV/local fallback and uses replace actions',()=>{const gasLoad=store.slice(store.indexOf('async function _loadFromGasSheet'),store.indexOf('async function _loadFromLocalCsvDb'));assert.doesNotMatch(gasLoad,/loadCsvDb|_saveLocal|localStorage/);const gasInit=store.slice(store.indexOf("if (_dataMode === 'gasSheet')"),store.indexOf('const alreadySeeded'));assert.doesNotMatch(gasInit,/fallback|localStorage/);assert.match(store,/callGasMutation\('replaceCollection'/);assert.match(store,/callGasMutation\('replaceCollectionsBatch'/);});
