import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const config=read('gas/00_Config.gs'),repo=read('gas/02_SheetRepository.gs'),validation=read('gas/03_Validation.gs'),api=read('gas/04_Api.gs');
test('request context centralizes config, spreadsheet, sheets, headers and collections',()=>{assert.match(config,/function createRequestContext_/);assert.equal((repo.match(/SpreadsheetApp\.openById/g)||[]).length,1);assert.match(repo,/ctx\.sheets\[key\]/);assert.match(repo,/ctx\.headers\[key\]/);assert.match(repo,/ctx\.collections\[key\]/);assert.match(api,/var ctx=createRequestContext_\(\)/);});
test('replace whitelist excludes optional name collections',()=>{const line=config.match(/PTB_REPLACEABLE_COLLECTIONS[^\n]+/)[0];['budgets','units','hourSettings','calendarPeriods','calendarRows','calendarHolidays','salaryEntries','forecastEvaluations'].forEach(name=>assert.match(line,new RegExp(name+':true')));assert.doesNotMatch(line,/scheduleTypes|holidayNames/);});
test('write mode, one Script Lock, validation-before-write and bulk repository are preserved',()=>{assert.match(repo,/assertWriteEnabled_\(ctx\)/);assert.match(repo,/LockService\.getScriptLock/);assert.match(api,/normalizeAndValidateCollections_[\s\S]*replaceTableRows_/);const replace=repo.slice(repo.indexOf('function replaceTableRows_'),repo.indexOf('function appendRecord_'));assert.equal((replace.match(/\.setValues\(/g)||[]).length,1);assert.doesNotMatch(replace,/appendRow|deleteRow/);});
test('salary validation keeps direct actualAmount and enforces composite uniqueness',()=>{assert.match(validation,/r\.actualAmount=finiteNonNegative_\(r\.actualAmount,'actualAmount'\)/);assert.doesNotMatch(validation,/actualAmount\s*=\s*r\.actualHours\s*\*/);assert.match(validation,/\[r\.academicYear,r\.year,r\.month,r\.unitCode\]/);});
test('salary duplicate diagnostic pure function is read-only',()=>{const source=`${validation}; return inspectSalaryEntryDuplicateKeys_;`;const fn=new Function('ptbError_','getTableDef_','readTable_','nowIso_','createId_',source)(()=>{},()=>({headers:[]}),()=>[],()=>'',()=> '');const rows=[{id:'A',academicYear:'114',year:2025,month:7,unitCode:'U'},{id:'B',academicYear:'114',year:2025,month:7,unitCode:'U'}],before=JSON.stringify(rows);assert.deepEqual(fn(rows),[{key:'114|2025|7|U',ids:['A','B'],rowCount:2}]);assert.equal(JSON.stringify(rows),before);});
test('hour combination expansion needs no new GAS action and existing validation protects source identity',()=>{const store=read('js/dataStore.js'),actions=api.match(/var PTB_ACTIONS[^\n]+/)[0];assert.match(store,/saveHourSettingCombinations[\s\S]*mutateCollection\('hourSettings'/);assert.doesNotMatch(actions,/saveHourSettingCombinations/);assert.match(validation,/sourceHourSettingId[\s\S]*sourceHourSettingId 不符/);assert.match(validation,/\[r\.academicYear,r\.scheduleType,r\.unitCode,r\.weekdays,r\.startTime,r\.endTime\]/);});
