from playwright.sync_api import sync_playwright
import json, sys
BASE = "http://127.0.0.1:5500/local.html"
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True);page=browser.new_page();page.goto(BASE,wait_until='networkidle');page.evaluate("""() => {localStorage.setItem('workStudy_seeded','true');localStorage.setItem('workStudy_budgets',JSON.stringify([{id:'B',academicYear:'114',budgetName:'G',unitCodes:['U']}])) ;localStorage.setItem('workStudy_units',JSON.stringify([{id:'U1',unitCode:'U',unitName:'Unit'}]));localStorage.setItem('workStudy_scheduleTypes',JSON.stringify([{id:'S',name:'平日'}]));localStorage.setItem('workStudy_hourSettings','[]')}""");page.reload(wait_until='networkidle');page.click('text=時數設定');page.click('#btn-add-hour');page.select_option('#hour-academicYear','114');page.select_option('#hour-budget-group','B');page.wait_for_timeout(100)
    checks=page.evaluate("""() => ({saveButtons:document.querySelectorAll('#hour-save-btn').length,scheduleSelectAbsent:!document.querySelector('select#hour-scheduleType'),unitSelectAbsent:!document.querySelector('select#hour-unit'),scheduleButtons:[...document.querySelectorAll('div#hour-scheduleType .weekday-btn')].filter(e=>e.checkVisibility()).length,unitButtons:[...document.querySelectorAll('div#hour-unit .weekday-btn')].filter(e=>e.checkVisibility()).length,patchLoaded:!!document.querySelector('[data-ptb156-hour-form-patched]')})""")
    source=page.locator('body').evaluate("async () => (await (await fetch('/js/hourSettingPage.js')).text())");enh=page.locator('body').evaluate("async () => (await (await fetch('/js/ptb156Enhancements.js')).text())");browser.close()
checks.update({'oneEditingOwner':source.count('let currentEditingId')==1,'noCloneReplace':all(x not in source+enh for x in ('cloneNode(true)','replaceWith(')),'atomicCombinationSave':'saveHourSettingCombinations({' in source})
ok=checks['saveButtons']==1 and checks['scheduleSelectAbsent'] and checks['unitSelectAbsent'] and checks['scheduleButtons']>0 and checks['unitButtons']>0 and not checks['patchLoaded'] and all(checks[k] for k in ('oneEditingOwner','noCloneReplace','atomicCombinationSave'));print(json.dumps({'status':'PASS' if ok else 'FAIL','checks':checks},ensure_ascii=False));sys.exit(0 if ok else 1)
