function cleanString_(v){return String(v===null||v===undefined?'':v).trim();}
function finiteNonNegative_(v,name){var n=Number(v);if(!isFinite(n)||n<0)throw ptbError_('VALIDATION_ERROR',name+' 必須是有限非負數');return n;}
function requireFields_(o,fields){fields.forEach(function(k){if(o[k]===null||o[k]===undefined||cleanString_(o[k])==='')throw ptbError_('VALIDATION_ERROR','缺少必要欄位：'+k);});}
function resolveUnitAndBudget_(academicYear,unitCode){var ay=cleanString_(academicYear),code=cleanString_(unitCode),units=readTable_('units').filter(function(u){return u.unitCode===code;}),matches=readTable_('budgets').filter(function(b){return b.academicYear===ay&&Array.isArray(b.unitCodes)&&b.unitCodes.indexOf(code)>=0&&b.budgetName;});if(units.length!==1)throw ptbError_('INVALID_UNIT','單位不存在或重複');if(matches.length===0)throw ptbError_('OUT_OF_BUDGET_SCOPE','單位不屬於預算群組');if(matches.length>1)throw ptbError_('BUDGET_SCOPE_ANOMALY','單位同時屬於多個預算群組');return {unit:units[0],budget:matches[0]};}
function validateRecord_(key,input,existing){var r=Object.assign({},input),scope;if(key==='budgets'){requireFields_(r,['academicYear','budgetName','budgetAmount']);r.academicYear=cleanString_(r.academicYear);r.budgetName=cleanString_(r.budgetName);r.unitCodes=[].concat(r.unitCodes||[]).map(cleanString_).filter(function(v,i,a){return v&&a.indexOf(v)===i;});if(!r.unitCodes.length)throw ptbError_('VALIDATION_ERROR','unitCodes 不可空白');r.budgetAmount=finiteNonNegative_(r.budgetAmount,'budgetAmount');var units=readTable_('units').map(function(u){return u.unitCode;});r.unitCodes.forEach(function(c){if(units.indexOf(c)<0)throw ptbError_('INVALID_UNIT','預算包含不存在的單位：'+c);});readTable_('budgets').filter(function(b){return !existing||b.id!==existing.id;}).forEach(function(b){if(b.academicYear===r.academicYear&&b.budgetName===r.budgetName)throw ptbError_('DUPLICATE','同年度預算名稱重複');if(b.academicYear===r.academicYear&&b.unitCodes.some(function(c){return r.unitCodes.indexOf(c)>=0;}))throw ptbError_('DUPLICATE','同年度單位已屬於其他預算群組');});}
else if(key==='hourSettings'){requireFields_(r,['academicYear','scheduleType','unitCode','weekdays','startTime','endTime','hours','hourlyWage']);scope=resolveUnitAndBudget_(r.academicYear,r.unitCode);r.unitName=scope.unit.unitName;r.hours=finiteNonNegative_(r.hours,'hours');r.hourlyWage=finiteNonNegative_(r.hourlyWage,'hourlyWage');var dup=['academicYear','scheduleType','unitCode','weekdays','startTime','endTime'];readTable_(key).forEach(function(x){if((!existing||x.id!==existing.id)&&dup.every(function(k){return cleanString_(x[k])===cleanString_(r[k]);}))throw ptbError_('DUPLICATE','時數設定重複');});}
else if(key==='calendarRows'){requireFields_(r,['date','academicYear','scheduleType','unitCode','sourceHourSettingId']);var src=readTable_('hourSettings').filter(function(x){return x.id===r.sourceHourSettingId;})[0];if(!src||src.academicYear!==cleanString_(r.academicYear)||src.unitCode!==cleanString_(r.unitCode)||src.scheduleType!==cleanString_(r.scheduleType))throw ptbError_('INVALID_SOURCE','sourceHourSettingId 不符');scope=resolveUnitAndBudget_(r.academicYear,r.unitCode);['unitName','startTime','endTime','hours','hourlyWage'].forEach(function(k){r[k]=src[k];});}
else if(key==='salaryEntries'){scope=resolveUnitAndBudget_(r.academicYear,r.unitCode);r.unitName=scope.unit.unitName;r.actualHours=finiteNonNegative_(r.actualHours,'actualHours');r.hourlyWage=finiteNonNegative_(r.hourlyWage,'hourlyWage');r.actualAmount=r.actualHours*r.hourlyWage;}
else if(key==='forecastEvaluations'){if(!Array.isArray(r.intervals))throw ptbError_('VALIDATION_ERROR','intervals 必須為 array');r.budget=finiteNonNegative_(r.budget,'budget');r.baseHourlyWage=finiteNonNegative_(r.baseHourlyWage,'baseHourlyWage');}
else if(key==='units'){requireFields_(r,['unitCode','unitName']);r.unitCode=cleanString_(r.unitCode);r.unitName=cleanString_(r.unitName);}
else if(key==='calendarPeriods'){requireFields_(r,['date']);r.date=cleanString_(r.date);}
else if(key==='calendarHolidays'){requireFields_(r,['date','name']);r.date=cleanString_(r.date);r.name=cleanString_(r.name);}
else if(key==='scheduleTypes'||key==='holidayNames'){requireFields_(r,['name']);r.name=cleanString_(r.name);var duplicates=readTable_(key).filter(function(x){return (!existing||x.id!==existing.id)&&cleanString_(x.name).toLowerCase()===r.name.toLowerCase();});if(duplicates.length)throw ptbError_('DUPLICATE','名稱已存在');}
return r;}
