function cleanString_(v){return String(v===null||v===undefined?'':v).trim();}
function finiteNonNegative_(v,name){var n=Number(v);if(!isFinite(n)||n<0)throw ptbError_('VALIDATION_ERROR',name+' 必須是有限非負數');return n;}
function finitePositive_(v,name){var n=Number(v);if(!isFinite(n)||n<=0)throw ptbError_('VALIDATION_ERROR',name+' 必須是大於 0 的有限數');return n;}
function requireFields_(o,fields){fields.forEach(function(k){if(o[k]===null||o[k]===undefined||cleanString_(o[k])==='')throw ptbError_('VALIDATION_ERROR','缺少必要欄位：'+k);});}
function uniqueBy_(rows,keyFn,message){var seen={};rows.forEach(function(r){var k=keyFn(r);if(seen[k])throw ptbError_('DUPLICATE',message,{key:k});seen[k]=true;});}
function validDate_(value){var text=cleanString_(value),match=text.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!match)return false;var year=Number(match[1]),month=Number(match[2]),day=Number(match[3]),date=new Date(Date.UTC(year,month-1,day));return date.getUTCFullYear()===year&&date.getUTCMonth()===month-1&&date.getUTCDate()===day;}
function safeInput_(input,key){if(!input||Object.prototype.toString.call(input)!=='[object Object]')throw ptbError_('VALIDATION_ERROR',key+' row 必須是 object');['__proto__','prototype','constructor'].forEach(function(k){if(Object.prototype.hasOwnProperty.call(input,k))throw ptbError_('UNSAFE_FIELD','不允許的欄位：'+k);});var out={},headers=getTableDef_(key).headers;headers.forEach(function(h){if(Object.prototype.hasOwnProperty.call(input,h))out[h]=input[h];});return out;}
function normalizeCandidateRows_(ctx,key,candidate){
  if(!PTB_REPLACEABLE_COLLECTIONS[key])throw ptbError_('INVALID_COLLECTION','不允許 replace collection',{collection:key});
  if(!Array.isArray(candidate))throw ptbError_('VALIDATION_ERROR','rows 必須是 array');
  var headers=getTableDef_(key).headers,hasCreatedAt=headers.indexOf('createdAt')>=0,hasUpdatedAt=headers.indexOf('updatedAt')>=0,current=readTable_(key,ctx),byId={},now=nowIso_();current.forEach(function(r){byId[r.id]=projectRecordToSchema_(key,r);});
  var rows=candidate.map(function(raw){var r=safeInput_(raw,key),id=cleanString_(r.id),existing=id&&byId[id];if(!id)id=createId_(key);else if(!existing&&!/^[A-Z]{2,8}_[A-Za-z0-9-]{8,}$/.test(id))id=createId_(key);r.id=id;if(hasCreatedAt)r.createdAt=existing?existing.createdAt:now;if(hasUpdatedAt)r.updatedAt=existing&&JSON.stringify(Object.assign({},existing,{updatedAt:''}))===JSON.stringify(Object.assign({},r,{updatedAt:''}))?existing.updatedAt:now;return projectRecordToSchema_(key,r);});
  uniqueBy_(rows,function(r){return r.id;},'id 不可重複');return rows;
}
function resolveUnitAndBudgetFrom_(academicYear,unitCode,units,budgets){var ay=cleanString_(academicYear),code=cleanString_(unitCode),u=units.filter(function(x){return cleanString_(x.unitCode)===code;}),b=budgets.filter(function(x){return cleanString_(x.academicYear)===ay&&Array.isArray(x.unitCodes)&&x.unitCodes.indexOf(code)>=0&&cleanString_(x.budgetName);});if(u.length!==1)throw ptbError_('INVALID_UNIT','單位不存在或重複');if(!b.length)throw ptbError_('OUT_OF_BUDGET_SCOPE','單位不屬於預算群組');if(b.length>1)throw ptbError_('BUDGET_SCOPE_ANOMALY','單位同時屬於多個預算群組');return {unit:u[0],budget:b[0]};}
function validateCandidateCollections_(ctx,candidates){
  var get=function(key){return candidates[key]||readTable_(key,ctx);},units=get('units'),budgets=get('budgets'),hours=get('hourSettings'),periods=get('calendarPeriods'),calendarRows=get('calendarRows'),holidays=get('calendarHolidays'),salaries=get('salaryEntries'),forecasts=get('forecastEvaluations');
  units.forEach(function(r){requireFields_(r,['unitCode','unitName']);r.unitCode=cleanString_(r.unitCode);r.unitName=cleanString_(r.unitName);});uniqueBy_(units,function(r){return r.unitCode;},'unitCode 不可重複');
  budgets.forEach(function(r){requireFields_(r,['academicYear','budgetName','budgetAmount']);r.academicYear=cleanString_(r.academicYear);r.budgetName=cleanString_(r.budgetName);r.budgetAmount=finiteNonNegative_(r.budgetAmount,'budgetAmount');if(!Array.isArray(r.unitCodes)||!r.unitCodes.length)throw ptbError_('VALIDATION_ERROR','unitCodes 不可空白');r.unitCodes=r.unitCodes.map(cleanString_);uniqueBy_(r.unitCodes,function(v){return v;},'unitCodes 不可重複');r.unitCodes.forEach(function(code){if(!units.some(function(u){return u.unitCode===code;}))throw ptbError_('INVALID_UNIT','預算包含不存在的單位：'+code);});});
  uniqueBy_(budgets,function(r){return r.academicYear+'|'+r.budgetName;},'同年度預算名稱重複');var budgetUnits={};budgets.forEach(function(r){r.unitCodes.forEach(function(code){var k=r.academicYear+'|'+code;if(budgetUnits[k])throw ptbError_('DUPLICATE','同年度單位已屬於其他預算群組');budgetUnits[k]=true;});});
  hours.forEach(function(r){requireFields_(r,['academicYear','scheduleType','unitCode','weekdays','startTime','endTime','hours']);var scope=resolveUnitAndBudgetFrom_(r.academicYear,r.unitCode,units,budgets);r.unitName=scope.unit.unitName;r.hours=finiteNonNegative_(r.hours,'hours');if(cleanString_(r.startTime)>=cleanString_(r.endTime))throw ptbError_('VALIDATION_ERROR','startTime 必須小於 endTime');if(!cleanString_(r.weekdays))throw ptbError_('VALIDATION_ERROR','weekdays 不可空白');});uniqueBy_(hours,function(r){return [r.academicYear,r.scheduleType,r.unitCode,r.weekdays,r.startTime,r.endTime].map(cleanString_).join('|');},'時數設定重複');
  periods.forEach(function(r){requireFields_(r,['date']);if(!validDate_(r.date))throw ptbError_('VALIDATION_ERROR','date 格式錯誤');});uniqueBy_(periods,function(r){return r.date;},'calendar period date 重複');
  calendarRows.forEach(function(r){requireFields_(r,['date','academicYear','scheduleType','unitCode','sourceHourSettingId','hourlyWage']);if(!validDate_(r.date))throw ptbError_('VALIDATION_ERROR','date 格式錯誤');var src=hours.filter(function(x){return x.id===r.sourceHourSettingId;})[0];if(!src||cleanString_(src.academicYear)!==cleanString_(r.academicYear)||cleanString_(src.unitCode)!==cleanString_(r.unitCode)||cleanString_(src.scheduleType)!==cleanString_(r.scheduleType))throw ptbError_('INVALID_SOURCE','sourceHourSettingId 不符');resolveUnitAndBudgetFrom_(r.academicYear,r.unitCode,units,budgets);['unitName','startTime','endTime','hours'].forEach(function(k){r[k]=src[k];});r.hourlyWage=finitePositive_(r.hourlyWage,'hourlyWage');});uniqueBy_(calendarRows,function(r){return [r.date,r.academicYear,r.scheduleType,r.unitCode,r.startTime,r.endTime].map(cleanString_).join('|');},'行事曆作息重複');
  holidays.forEach(function(r){requireFields_(r,['date','name']);if(!validDate_(r.date))throw ptbError_('VALIDATION_ERROR','holiday date 格式錯誤');r.name=cleanString_(r.name);});uniqueBy_(holidays,function(r){return r.date;},'holiday date 重複');
  salaries.forEach(function(r){requireFields_(r,['academicYear','year','month','unitCode','actualAmount']);var scope=resolveUnitAndBudgetFrom_(r.academicYear,r.unitCode,units,budgets);r.unitName=scope.unit.unitName;r.year=Number(r.year);r.month=Number(r.month);if(!Number.isInteger(r.year)||!Number.isInteger(r.month)||r.month<1||r.month>12)throw ptbError_('VALIDATION_ERROR','薪資年月錯誤');r.actualAmount=finiteNonNegative_(r.actualAmount,'actualAmount');r.actualHours=r.actualHours===''||r.actualHours===undefined?0:finiteNonNegative_(r.actualHours,'actualHours');r.hourlyWage=r.hourlyWage===''||r.hourlyWage===undefined?0:finiteNonNegative_(r.hourlyWage,'hourlyWage');});uniqueBy_(salaries,function(r){return [r.academicYear,r.year,r.month,r.unitCode].map(cleanString_).join('|');},'薪資複合鍵重複');
  forecasts.forEach(function(r){requireFields_(r,['name','budget']);r.name=cleanString_(r.name);if(!Array.isArray(r.intervals))throw ptbError_('VALIDATION_ERROR','intervals 必須為 array');r.intervals=r.intervals.map(function(i){if(!i||typeof i!=='object'||Array.isArray(i))throw ptbError_('VALIDATION_ERROR','intervals item 必須是 object');var start=cleanString_(i.startYm),end=cleanString_(i.endYm),wage=finiteNonNegative_(i.hourlyWage,'interval.hourlyWage');if(!/^\d{4}-\d{2}$/.test(start)||!/^\d{4}-\d{2}$/.test(end)||start>end)throw ptbError_('VALIDATION_ERROR','interval 年月區間錯誤');return {startYm:start,endYm:end,hourlyWage:wage,note:cleanString_(i.note)};});r.budget=finiteNonNegative_(r.budget,'budget');r.baseHourlyWage=finiteNonNegative_(r.baseHourlyWage===undefined||r.baseHourlyWage===''?0:r.baseHourlyWage,'baseHourlyWage');});
  var hourIds={};hours.forEach(function(r){hourIds[r.id]=true;});calendarRows.forEach(function(r){if(!hourIds[r.sourceHourSettingId])throw ptbError_('REFERENCE_IN_USE','calendarRows 引用不存在的 hour setting');});
  return candidates;
}
function normalizeAndValidateCollections_(ctx,raw){var candidates={};Object.keys(raw).forEach(function(key){candidates[key]=normalizeCandidateRows_(ctx,key,raw[key]);});validateCandidateCollections_(ctx,candidates);return candidates;}
function resolveUnitAndBudget_(academicYear,unitCode,ctx){return resolveUnitAndBudgetFrom_(academicYear,unitCode,readTable_('units',ctx),readTable_('budgets',ctx));}
function validateRecord_(key,input,existing,ctx){var candidate=readTable_(key,ctx).filter(function(r){return !existing||r.id!==existing.id;});candidate.push(Object.assign({},input,existing?{id:existing.id}:{}));return normalizeAndValidateCollections_(ctx,(function(){var o={};o[key]=candidate;return o;}()))[key].slice(-1)[0];}
function inspectSalaryEntryDuplicateKeys_(rows){var map={};(rows||[]).forEach(function(r){var key=[r.academicYear,r.year,r.month,r.unitCode].map(cleanString_).join('|');if(!map[key])map[key]=[];map[key].push(r.id);});return Object.keys(map).filter(function(k){return map[k].length>1;}).map(function(k){return {key:k,ids:map[k],rowCount:map[k].length};});}
